replicaCount: 1

image:
  repository: shrirang451/amazon-prime
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

app:
  name: nginx-app
  containerName: nginx-container
